replicaCount: 2   #changed to test ArgoCD
image: 
  repository: abdulrahmanqasim/multiplats-github-test
  tag: main
service:
 # type: NodePort use this in case you didn't use any Loadbalance
  type: ClusterIP
  port: 5000
  targetPort: 5000
  nodePort: 30008
mariadb:
  image: mariadb:12
  rootPassword: "1234Root"
  database: "My_maria"
  username: "maria"
  password: "AppSecrets"
config:
  name: flask-config
  flask_app: "run.py"
  flaskEnv: "dev"
secret:
  name: flask-secret

storage:
  claimname: profile-pictures-pvc
  size: 500Mi
  databaseSize: 1Gi

resources:
     requests:
       cpu: "100m"
       memory: "128Mi"
     limits:
        cpu: "500m"
        memory: "512Mi"
hpa:
  minReplicas: 1
  maxReplicas: 2
  cpuUtil: 80
